// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parduotuve.Core.Repositories;

#nullable disable

namespace Parduotuve.Core.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240826112846_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Parduotuve.Core.Models.Pardavejas", b =>
                {
                    b.Property<int>("PardavejoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PardavejoId"));

                    b.Property<string>("ElPastas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelNumeris")
                        .HasColumnType("int");

                    b.Property<string>("Tipas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PardavejoId");

                    b.ToTable("Pardavejai");
                });

            modelBuilder.Entity("Parduotuve.Core.Models.Pirkejas", b =>
                {
                    b.Property<int>("PirkejoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PirkejoId"));

                    b.Property<string>("ElPastas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TelNumeris")
                        .HasColumnType("int");

                    b.Property<string>("Tipas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PirkejoId");

                    b.ToTable("Pirkejai");
                });

            modelBuilder.Entity("Parduotuve.Core.Models.Produktas", b =>
                {
                    b.Property<int>("ProduktoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProduktoId"));

                    b.Property<decimal>("Kaina")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Kategorija")
                        .HasColumnType("int");

                    b.Property<int>("KiekisSandelyje")
                        .HasColumnType("int");

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProduktoId");

                    b.ToTable("Produktai");
                });

            modelBuilder.Entity("Parduotuve.Core.Models.Uzsakymas", b =>
                {
                    b.Property<int>("UzsakymoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UzsakymoId"));

                    b.Property<int>("Kiekis")
                        .HasColumnType("int");

                    b.Property<int>("PardavejoId")
                        .HasColumnType("int");

                    b.Property<int>("PirkejoId")
                        .HasColumnType("int");

                    b.Property<int>("ProduktoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UzsakymoData")
                        .HasColumnType("date");

                    b.HasKey("UzsakymoId");

                    b.ToTable("Uzsakymai");
                });
#pragma warning restore 612, 618
        }
    }
}
